/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ClaimCodeRouteImport } from './routes/claim/$code'
import { Route as DecksIndexRouteImport } from './routes/decks/index'
import { Route as DecksDeckIdRouteImport } from './routes/decks/$deckId'
import { Route as DecksNewRouteImport } from './routes/decks/new'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsNewRouteImport } from './routes/events/new'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOgDefaultRouteImport } from './routes/api/og/default'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsEventIdScreenRouteImport } from './routes/events/$eventId/screen'
import { Route as ApiOgEventEventIdRouteImport } from './routes/api/og/event.$eventId'
import { Route as ApiOgPlayerUsernameRouteImport } from './routes/api/og/player.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimCodeRoute = ClaimCodeRouteImport.update({
  id: '/claim/$code',
  path: '/claim/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksNewRoute = DecksNewRouteImport.update({
  id: '/decks/new',
  path: '/decks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgDefaultRoute = ApiOgDefaultRouteImport.update({
  id: '/api/og/default',
  path: '/api/og/default',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdScreenRoute = EventsEventIdScreenRouteImport.update({
  id: '/events/$eventId/screen',
  path: '/events/$eventId/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgEventEventIdRoute = ApiOgEventEventIdRouteImport.update({
  id: '/api/og/event/$eventId',
  path: '/api/og/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgPlayerUsernameRoute = ApiOgPlayerUsernameRouteImport.update({
  id: '/api/og/player/$username',
  path: '/api/og/player/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/claim/$code': typeof ClaimCodeRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/new': typeof DecksNewRoute
  '/events/new': typeof EventsNewRoute
  '/join/$code': typeof JoinCodeRoute
  '/u/$username': typeof UUsernameRoute
  '/decks/': typeof DecksIndexRoute
  '/events/': typeof EventsIndexRoute
  '/join/': typeof JoinIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/default': typeof ApiOgDefaultRoute
  '/events/$eventId/screen': typeof EventsEventIdScreenRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/api/og/event/$eventId': typeof ApiOgEventEventIdRoute
  '/api/og/player/$username': typeof ApiOgPlayerUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/claim/$code': typeof ClaimCodeRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/new': typeof DecksNewRoute
  '/events/new': typeof EventsNewRoute
  '/join/$code': typeof JoinCodeRoute
  '/u/$username': typeof UUsernameRoute
  '/decks': typeof DecksIndexRoute
  '/events': typeof EventsIndexRoute
  '/join': typeof JoinIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/default': typeof ApiOgDefaultRoute
  '/events/$eventId/screen': typeof EventsEventIdScreenRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/api/og/event/$eventId': typeof ApiOgEventEventIdRoute
  '/api/og/player/$username': typeof ApiOgPlayerUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/claim/$code': typeof ClaimCodeRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/new': typeof DecksNewRoute
  '/events/new': typeof EventsNewRoute
  '/join/$code': typeof JoinCodeRoute
  '/u/$username': typeof UUsernameRoute
  '/decks/': typeof DecksIndexRoute
  '/events/': typeof EventsIndexRoute
  '/join/': typeof JoinIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/default': typeof ApiOgDefaultRoute
  '/events/$eventId/screen': typeof EventsEventIdScreenRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/api/og/event/$eventId': typeof ApiOgEventEventIdRoute
  '/api/og/player/$username': typeof ApiOgPlayerUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/api/uploadthing'
    | '/claim/$code'
    | '/decks/$deckId'
    | '/decks/new'
    | '/events/new'
    | '/join/$code'
    | '/u/$username'
    | '/decks/'
    | '/events/'
    | '/join/'
    | '/api/auth/$'
    | '/api/og/default'
    | '/events/$eventId/screen'
    | '/events/$eventId/'
    | '/api/og/event/$eventId'
    | '/api/og/player/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/api/uploadthing'
    | '/claim/$code'
    | '/decks/$deckId'
    | '/decks/new'
    | '/events/new'
    | '/join/$code'
    | '/u/$username'
    | '/decks'
    | '/events'
    | '/join'
    | '/api/auth/$'
    | '/api/og/default'
    | '/events/$eventId/screen'
    | '/events/$eventId'
    | '/api/og/event/$eventId'
    | '/api/og/player/$username'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/api/uploadthing'
    | '/claim/$code'
    | '/decks/$deckId'
    | '/decks/new'
    | '/events/new'
    | '/join/$code'
    | '/u/$username'
    | '/decks/'
    | '/events/'
    | '/join/'
    | '/api/auth/$'
    | '/api/og/default'
    | '/events/$eventId/screen'
    | '/events/$eventId/'
    | '/api/og/event/$eventId'
    | '/api/og/player/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ClaimCodeRoute: typeof ClaimCodeRoute
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  DecksNewRoute: typeof DecksNewRoute
  EventsNewRoute: typeof EventsNewRoute
  JoinCodeRoute: typeof JoinCodeRoute
  UUsernameRoute: typeof UUsernameRoute
  DecksIndexRoute: typeof DecksIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  JoinIndexRoute: typeof JoinIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOgDefaultRoute: typeof ApiOgDefaultRoute
  EventsEventIdScreenRoute: typeof EventsEventIdScreenRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  ApiOgEventEventIdRoute: typeof ApiOgEventEventIdRoute
  ApiOgPlayerUsernameRoute: typeof ApiOgPlayerUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$code': {
      id: '/claim/$code'
      path: '/claim/$code'
      fullPath: '/claim/$code'
      preLoaderRoute: typeof ClaimCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/new': {
      id: '/decks/new'
      path: '/decks/new'
      fullPath: '/decks/new'
      preLoaderRoute: typeof DecksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/default': {
      id: '/api/og/default'
      path: '/api/og/default'
      fullPath: '/api/og/default'
      preLoaderRoute: typeof ApiOgDefaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/screen': {
      id: '/events/$eventId/screen'
      path: '/events/$eventId/screen'
      fullPath: '/events/$eventId/screen'
      preLoaderRoute: typeof EventsEventIdScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/event/$eventId': {
      id: '/api/og/event/$eventId'
      path: '/api/og/event/$eventId'
      fullPath: '/api/og/event/$eventId'
      preLoaderRoute: typeof ApiOgEventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/player/$username': {
      id: '/api/og/player/$username'
      path: '/api/og/player/$username'
      fullPath: '/api/og/player/$username'
      preLoaderRoute: typeof ApiOgPlayerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ClaimCodeRoute: ClaimCodeRoute,
  DecksDeckIdRoute: DecksDeckIdRoute,
  DecksNewRoute: DecksNewRoute,
  EventsNewRoute: EventsNewRoute,
  JoinCodeRoute: JoinCodeRoute,
  UUsernameRoute: UUsernameRoute,
  DecksIndexRoute: DecksIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  JoinIndexRoute: JoinIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOgDefaultRoute: ApiOgDefaultRoute,
  EventsEventIdScreenRoute: EventsEventIdScreenRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  ApiOgEventEventIdRoute: ApiOgEventEventIdRoute,
  ApiOgPlayerUsernameRoute: ApiOgPlayerUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
